import FontLoader from '@/components/FontLoader'
import './globals.css'
import { Header } from '@/components/Header'
import { ToasterComponent } from '@/components/Alerts/ToasterComponent'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html lang="en">
        <body className="max-w-full w-full min-h-screen bg-gray900">
          <Header />
          <main>{children}</main>
          <ToasterComponent />
        </body>
      </html>
      <FontLoader />
    </>
  )
}
