import './globals.css'
import FontLoader from '@/components/FontLoader'
import { Header } from '@/components/Header'
import { ToasterComponent } from '@/components/Alerts/ToasterComponent'
import AppContextProvider from '@/contexts/AppContext'
import { AddPost } from '@/components/AddPost/AddPost'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      <html lang="en">
        <AppContextProvider>
          <body className="max-w-full w-full min-h-screen bg-gray900">
            <Header />

            <AddPost />

            <main>{children}</main>
            <ToasterComponent />
          </body>
        </AppContextProvider>
      </html>
      <FontLoader />
    </>
  )
}
